# General declaration
spring.application.name=${APP_NAME}
server.port=${PORT}

# Database connection
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=${DDL_AUTO}
spring.jpa.show-sql=${SHOW_SQL}

# Eureka configuration
eureka.client.service-url.defaultZone=${EUREKA_URL}
eureka.client.register-with-eureka=${EUREKA_REGISTER}
eureka.client.fetch-registry=${EUREKA_FETCH}
eureka.instance.prefer-ip-address=${PREFER_IP}

# Mail Configuration
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_STARTTLS}
